# Generated by Django 2.1 on 2018-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_merge_20180816_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='district',
            field=models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('ptm', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('mpm', 'Malappuram'), ('koz', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('pkd', 'Palakkad'), ('tcr', 'Thrissur'), ('ekm', 'Ernakulam'), ('kol', 'Kollam')], db_index=True, max_length=15, verbose_name='Districts - ജില്ല'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Requestee - അപേക്ഷകന്\u200dറെ പേര്'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee_phone',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Requestee Phone - അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d'),
        ),
    ]
